<?php

return [
    'accounts' => [
        // I - Aset
        ['category' => 'AKTIVA', 'account_code' => '1', 'account_name' => 'AKTIVA', 'sub_category' => '-'],
        ['category' => 'AKTIVA', 'account_code' => '100', 'account_name' => 'Kas & Bank', 'sub_category' => 'Kas & Bank'],
        ['category' => 'AKTIVA', 'account_code' => '101', 'account_name' => 'Kas Utama', 'sub_category' => 'Kas & Bank'],
        ['category' => 'AKTIVA', 'account_code' => '102', 'account_name' => 'Petty Cash', 'sub_category' => 'Kas & Bank', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '103', 'account_name' => 'Cash in Transit', 'sub_category' => 'Kas & Bank', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '104', 'account_name' => 'Bank CV, AHA Right Brain', 'sub_category' => 'Kas & Bank', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '105', 'account_name' => 'Bank Lainnya', 'sub_category' => 'Kas & Bank', 'person_type' => 'Lisensi'],

        ['category' => 'AKTIVA', 'account_code' => '110', 'account_name' => 'Persediaan Barang', 'sub_category' => 'Persediaan Barang', 'person_type' => 'Lisensi'],

        ['category' => 'AKTIVA', 'account_code' => '120', 'account_name' => 'Piutang', 'sub_category' => 'Piutang', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '121', 'account_name' => 'Piutang Usaha', 'sub_category' => 'Piutang', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '122', 'account_name' => 'Piutang Karyawan', 'sub_category' => 'Piutang', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '123', 'account_name' => 'Piutang Siswa', 'sub_category' => 'Piutang', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '124', 'account_name' => 'Piutang Lain - Lain', 'sub_category' => 'Piutang', 'person_type' => 'Lisensi'],

        ['category' => 'AKTIVA', 'account_code' => '130', 'account_name' => 'Dana Belum Disetor', 'sub_category' => 'Dana Belum Disetor', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '131', 'account_name' => 'Uang Muka', 'sub_category' => 'Dana Belum Disetor', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '132', 'account_name' => 'Biaya Bayar Dimuka', 'sub_category' => 'Dana Belum Disetor', 'person_type' => 'Lisensi'],

        ['category' => 'AKTIVA', 'account_code' => '140', 'account_name' => 'Pajak Bayar Dimuka', 'sub_category' => 'Pajak Bayar Dimuka', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '141', 'account_name' => 'PPN Masukan', 'sub_category' => 'Pajak Bayar Dimuka', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '142', 'account_name' => 'Pajak Dibayar Dimuka - PPh 23', 'sub_category' => 'Pajak Bayar Dimuka', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '143', 'account_name' => 'Pajak Dibayar Dimuka - PPh 25', 'sub_category' => 'Pajak Bayar Dimuka', 'person_type' => 'Lisensi'],
        ['category' => 'AKTIVA', 'account_code' => '144', 'account_name' => 'Pajak Dibayar Dimuka Lainnya', 'sub_category' => 'Pajak Bayar Dimuka', 'person_type' => 'Lisensi'],

        ['category' => 'AKTIVA', 'account_code' => '150', 'account_name' => 'Aset Tetap', 'sub_category' => 'Aset Tetap', 'person_type' => 'Siswa'],
        ['category' => 'AKTIVA', 'account_code' => '151', 'account_name' => 'Tanah', 'sub_category' => 'Aset Tetap', 'person_type' => 'Karyawan'],
        ['category' => 'AKTIVA', 'account_code' => '152', 'account_name' => 'Bangunan', 'sub_category' => 'Aset Tetap', 'person_type' => 'Siswa'],
        ['category' => 'AKTIVA', 'account_code' => '153', 'account_name' => 'Kendaraan', 'sub_category' => 'Aset Tetap', 'person_type' => 'Karyawan'],
        ['category' => 'AKTIVA', 'account_code' => '154', 'account_name' => 'Perlengkapan Kantor', 'sub_category' => 'Aset Tetap', 'person_type' => 'Siswa'],
        ['category' => 'AKTIVA', 'account_code' => '155', 'account_name' => 'Aset Tidak Berwujud', 'sub_category' => 'Aset Tetap', 'person_type' => 'Karyawan'],

        ['category' => 'AKTIVA', 'account_code' => '160', 'account_name' => 'Penyusutan', 'sub_category' => 'Penyusutan', 'person_type' => 'Siswa'],
        ['category' => 'AKTIVA', 'account_code' => '161', 'account_name' => 'Penyusutan Bangunan', 'sub_category' => 'Penyusutan', 'person_type' => 'Karyawan'],
        ['category' => 'AKTIVA', 'account_code' => '162', 'account_name' => 'Penyusutan Kendaraan', 'sub_category' => 'Penyusutan', 'person_type' => 'Siswa'],
        ['category' => 'AKTIVA', 'account_code' => '163', 'account_name' => 'Penyusutan Perlengkapan Kantor', 'sub_category' => 'Penyusutan', 'person_type' => 'Karyawan'],

        // II - KEWAJIBAN
        ['category' => 'KEWAJIBAN', 'account_code' => '2', 'account_name' => 'KEWAJIBAN', 'sub_category' => '-'],
        ['category' => 'KEWAJIBAN', 'account_code' => '200', 'account_name' => 'Hutang', 'sub_category' => 'Hutang', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '201', 'account_name' => 'Hutang Usaha', 'sub_category' => 'Hutang', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '202', 'account_name' => 'Hutang Gaji', 'sub_category' => 'Hutang', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '203', 'account_name' => 'Hutang Deviden', 'sub_category' => 'Hutang', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '204', 'account_name' => 'Hutang Pemegang Saham', 'sub_category' => 'Hutang', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '205', 'account_name' => 'Hutang Lain-Lain', 'sub_category' => 'Hutang', 'person_type' => 'Lisensi'],

        ['category' => 'KEWAJIBAN', 'account_code' => '210', 'account_name' => 'Uang Muka Penjualan', 'sub_category' => 'Uang Muka Penjualan', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '211', 'account_name' => 'Uang Muka Penjualan', 'sub_category' => 'Uang Muka Penjualan', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '212', 'account_name' => 'Pendapatan Diterima Dimuka', 'sub_category' => 'Uang Muka Penjualan'],

        ['category' => 'KEWAJIBAN', 'account_code' => '220', 'account_name' => 'Pajak', 'sub_category' => 'Pajak'],
        ['category' => 'KEWAJIBAN', 'account_code' => '221', 'account_name' => 'PPN Keluaran', 'sub_category' => 'Pajak'],
        ['category' => 'KEWAJIBAN', 'account_code' => '222', 'account_name' => 'Hutang Pajak PPh 23', 'sub_category' => 'Pajak'],
        ['category' => 'KEWAJIBAN', 'account_code' => '223', 'account_name' => 'Hutang Pajak PPh 25', 'sub_category' => 'Pajak', 'person_type' => 'Lisensi'],
        ['category' => 'KEWAJIBAN', 'account_code' => '224', 'account_name' => 'Hutang Pajak Lainnya', 'sub_category' => 'Pajak', 'person_type' => 'Lisensi'],

        ['category' => 'EKUITAS', 'account_code' => '3', 'account_name' => 'EKUITAS', 'sub_category' => '-'],
        ['category' => 'Ekuitas', 'account_code' => '300', 'account_name' => 'Modal', 'sub_category' => 'Modal', 'person_type' => 'Lisensi'],
        ['category' => 'Ekuitas', 'account_code' => '301', 'account_name' => 'Modal Saham', 'sub_category' => 'Modal', 'person_type' => 'Lisensi'],
        ['category' => 'Ekuitas', 'account_code' => '302', 'account_name' => 'Tambahan Modal Disetor', 'sub_category' => 'Modal'],
        ['category' => 'Ekuitas', 'account_code' => '303', 'account_name' => 'Laba Ditahan', 'sub_category' => 'Modal'],
        ['category' => 'Ekuitas', 'account_code' => '304', 'account_name' => 'Deviden', 'sub_category' => 'Modal'],

        ['category' => 'PENDAPATAN', 'account_code' => '4', 'account_name' => 'PENDAPATAN', 'sub_category' => '-'],
        ['category' => 'Pendapatan', 'account_code' => '400', 'account_name' => 'Pendapatan Lisensi', 'sub_category' => 'Pendapatan Lisensi', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '401', 'account_name' => 'Pembukaan Lisensi LC', 'sub_category' => 'Pendapatan Lisensi', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '402', 'account_name' => 'Pembukaan Lisensi LO', 'sub_category' => 'Pendapatan Lisensi', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '403', 'account_name' => 'Perpanjangan Lisensi LC', 'sub_category' => 'Pendapatan Lisensi', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '404', 'account_name' => 'Perpanjangan Lisensi LO', 'sub_category' => 'Pendapatan Lisensi'],

        ['category' => 'Pendapatan', 'account_code' => '410', 'account_name' => 'Pendapatan Modul', 'sub_category' => 'Pendapatan Modul'],
        ['category' => 'Pendapatan', 'account_code' => '411', 'account_name' => 'Penjualan Modul Prebasic', 'sub_category' => 'Pendapatan Modul'],
        ['category' => 'Pendapatan', 'account_code' => '412', 'account_name' => 'Penjualan Modul Basic', 'sub_category' => 'Pendapatan Modul'],
        ['category' => 'Pendapatan', 'account_code' => '413', 'account_name' => 'Penjualan Modul Intermediate', 'sub_category' => 'Pendapatan Modul', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '414', 'account_name' => 'Penjualan Modul Advance', 'sub_category' => 'Pendapatan Modul'],

        ['category' => 'Pendapatan', 'account_code' => '420', 'account_name' => 'Pendapatan Siswa', 'sub_category' => 'Pendapatan Siswa', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '421', 'account_name' => 'Pendaftaran Siswa', 'sub_category' => 'Pendapatan Siswa'],
        ['category' => 'Pendapatan', 'account_code' => '422', 'account_name' => 'SPP Siswa', 'sub_category' => 'Pendapatan Siswa', 'person_type' => 'Lisensi'],

        ['category' => 'Pendapatan', 'account_code' => '430', 'account_name' => 'Pendapatan Merchandise', 'sub_category' => 'Pendapatan Merchandise', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '431', 'account_name' => 'Penjualan Gelang Prebasic', 'sub_category' => 'Pendapatan Merchandise'],
        ['category' => 'Pendapatan', 'account_code' => '432', 'account_name' => 'Penjualan Gelang Basic', 'sub_category' => 'Pendapatan Merchandise'],
        ['category' => 'Pendapatan', 'account_code' => '433', 'account_name' => 'Penjualan Gelang Intermediate', 'sub_category' => 'Pendapatan Merchandise'],
        ['category' => 'Pendapatan', 'account_code' => '434', 'account_name' => 'Penjualan Gelang Advance', 'sub_category' => 'Pendapatan Merchandise'],
        ['category' => 'Pendapatan', 'account_code' => '435', 'account_name' => 'Penjualan Totebag Prebasic', 'sub_category' => 'Pendapatan Merchandise', 'person_type' => 'Karyawan'],
        ['category' => 'Pendapatan', 'account_code' => '436', 'account_name' => 'Penjualan Totebag Basic', 'sub_category' => 'Pendapatan Merchandise', 'person_type' => 'Karyawan'],
        ['category' => 'Pendapatan', 'account_code' => '437', 'account_name' => 'Penjualan Totebag Intermediate', 'sub_category' => 'Pendapatan Merchandise'],
        ['category' => 'Pendapatan', 'account_code' => '438', 'account_name' => 'Penjualan Totebag Advance', 'sub_category' => 'Pendapatan Merchandise', 'person_type' => 'Lisensi'],
        ['category' => 'Pendapatan', 'account_code' => '439', 'account_name' => 'Penjualan Kaos', 'sub_category' => 'Pendapatan Merchandise'],
        ['category' => 'Pendapatan', 'account_code' => '440', 'account_name' => 'Penjualan Gantungan Kunci', 'sub_category' => 'Pendapatan Merchandise'],

        ['category' => 'Pendapatan', 'account_code' => '450', 'account_name' => 'Pendapatan Lainnya', 'sub_category' => 'Pendapatan Lainnya'],
        ['category' => 'Pendapatan', 'account_code' => '451', 'account_name' => 'Training Instruktur', 'sub_category' => 'Pendapatan Lainnya'],
        ['category' => 'Pendapatan', 'account_code' => '452', 'account_name' => 'Pendapatan Lain-Lain', 'sub_category' => 'Pendapatan Lainnya'],
        ['category' => 'Pendapatan', 'account_code' => '453', 'account_name' => 'Diskon Penjualan', 'sub_category' => 'Pendapatan Lainnya'],
        ['category' => 'Pendapatan', 'account_code' => '454', 'account_name' => 'Retur Penjualan', 'sub_category' => 'Pendapatan Lainnya'],

        ['category' => 'BEBAN', 'account_code' => '5', 'account_name' => 'BEBAN', 'sub_category' => '-'],
        ['category' => 'BEBAN', 'account_code' => '500', 'account_name' => 'Biya Lisensi', 'sub_category' => 'Biaya Lisensi'],
        ['category' => 'BEBAN', 'account_code' => '501', 'account_name' => 'Biaya Pembukaan Lisensi LC', 'sub_category' => 'Biaya Lisensi'],
        ['category' => 'BEBAN', 'account_code' => '502', 'account_name' => 'Biaya Pembukaan Lisensi LO', 'sub_category' => 'Biaya Lisensi'],
        ['category' => 'BEBAN', 'account_code' => '503', 'account_name' => 'Biaya Perpanjangan Lisensi LC', 'sub_category' => 'Biaya Lisensi'],
        ['category' => 'BEBAN', 'account_code' => '504', 'account_name' => 'Biaya Perpanjangan Lisensi LO', 'sub_category' => 'Biaya Lisensi', 'person_type' => 'Siswa'],

        ['category' => 'BEBAN', 'account_code' => '510', 'account_name' => 'Biaya Pembelian Modul', 'sub_category' => 'Biaya Pembelian Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '511', 'account_name' => 'Biaya Beli Modul Prebasic', 'sub_category' => 'Biaya Pembelian Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '512', 'account_name' => 'Biaya Beli Modul Basic', 'sub_category' => 'Biaya Pembelian Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '513', 'account_name' => 'Biaya Beli Modul Intermediate', 'sub_category' => 'Biaya Pembelian Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '514', 'account_name' => 'Biaya Beli Modul Advance', 'sub_category' => 'Biaya Pembelian Modul', 'person_type' => 'Siswa'],

        ['category' => 'BEBAN', 'account_code' => '520', 'account_name' => 'Biaya Pembelian Merchandise', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '521', 'account_name' => 'Biaya Beli Gelang Prebasic', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '522', 'account_name' => 'Biaya Beli Gelang Basic', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '523', 'account_name' => 'Biaya Beli Gelang Intermediate', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '524', 'account_name' => 'Biaya Beli Gelang Advance', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '525', 'account_name' => 'Biaya Beli Totebag Prebasic', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '526', 'account_name' => 'Biaya Beli Totebag Basic', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '527', 'account_name' => 'Biaya Beli Totebag Intermediate', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '528', 'account_name' => 'Biaya Beli Totebag Advance', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '529', 'account_name' => 'Biaya Beli Gantungan Kunci', 'sub_category' => 'Biaya Pembelian Merchandise', 'person_type' => 'Siswa'],

        ['category' => 'BEBAN', 'account_code' => '550', 'account_name' => 'Biaya Produksi Modul', 'sub_category' => 'Biaya Produksi Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '551', 'account_name' => 'Biaya Cetak Modul Prebasic', 'sub_category' => 'Biaya Produksi Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '552', 'account_name' => 'Biaya Cetak Modul Basic', 'sub_category' => 'Biaya Produksi Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '553', 'account_name' => 'Biaya Cetak Modul Intermediate', 'sub_category' => 'Biaya Produksi Modul', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '554', 'account_name' => 'Biaya Cetak Modul Advance', 'sub_category' => 'Biaya Produksi Modul', 'person_type' => 'Siswa'],

        ['category' => 'BEBAN', 'account_code' => '560', 'account_name' => 'Biaya Produksi Merchandise', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '561', 'account_name' => 'Biaya Cetak Gelang Prebasic', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '562', 'account_name' => 'Biaya Cetak Gelang Basic', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '563', 'account_name' => 'Biaya Cetak Gelang Intermediate', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '564', 'account_name' => 'Biaya Cetak Gelang Advance', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '565', 'account_name' => 'Biaya Cetak Totebag Prebasic', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '566', 'account_name' => 'Biaya Cetak Totebag Basic', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '567', 'account_name' => 'Biaya Cetak Totebag Intermediate', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '568', 'account_name' => 'Biaya Cetak Totebag Advance', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '569', 'account_name' => 'Biaya Cetak Kaos', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],
        ['category' => 'BEBAN', 'account_code' => '570', 'account_name' => 'Biaya Cetak Gantungan Kunci', 'sub_category' => 'Biaya Produksi Merchandise', 'person_type' => 'Siswa'],

        ['category' => 'BEBAN', 'account_code' => '6', 'account_name' => 'BEBAN', 'sub_category' => '-'],
        ['category' => 'BEBAN', 'account_code' => '600', 'account_name' => 'Beban Penjualan & Pemasaran', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '601', 'account_name' => 'Biaya Transportasi', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '602', 'account_name' => 'Biaya Digital', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '603', 'account_name' => 'Biaya Packing', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '604', 'account_name' => 'Biaya Kirim Paket', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '605', 'account_name' => 'Biaya Marketing', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '606', 'account_name' => 'Biaya Event', 'sub_category' => 'Beban Penjualan & Pemasaran', 'person_type' => 'Siswa'],


        ['category' => 'Beban', 'account_code' => '610', 'account_name' => 'Beban Administrasi & Umum', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '611', 'account_name' => 'Biaya Training Instruktur', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '612', 'account_name' => 'Biaya Gaji', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '613', 'account_name' => 'Biaya Fee', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '614', 'account_name' => 'Biaya Bonus', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '615', 'account_name' => 'Biaya Konsumsi', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '616', 'account_name' => 'Biaya ATK & FC', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '617', 'account_name' => 'Biaya Listrik, Air, Pulsa, WiFi', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '618', 'account_name' => 'Biaya Perlengkapan Kantor', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '619', 'account_name' => 'Biaya FC, Print, dan Bendel', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '620', 'account_name' => 'Biaya Administrasi Rekening', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '621', 'account_name' => 'Biaya Sewa Ruko', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '622', 'account_name' => 'Biaya Kebersihan Lingkungan', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '623', 'account_name' => 'Biaya Keamanan', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '624', 'account_name' => 'Biaya Perbaikan', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '625', 'account_name' => 'Biaya Parkir', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '626', 'account_name' => 'Biaya Donasi', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
        ['category' => 'Beban', 'account_code' => '627', 'account_name' => 'Biaya Lain-Lain', 'sub_category' => 'Beban Administrasi & Umum', 'person_type' => 'Siswa'],
    ],
];