<?php

return [
    'accounts' => [
        // I - Pendapatan
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0001', 'account_name' => 'PEMBUKAAN (LISENSI) SUB LC (TINGKAT KEC)', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0002', 'account_name' => 'PEMBUKAAN (LISENSI) SUB LO (TINGKAT KAB)', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0003', 'account_name' => 'PERPANJANGAN (LISENSI) SUB LC (TINGKAT KEC)', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0004', 'account_name' => 'PERPANJANGAN (LISENSI) SUB LO (TINGKAT KAB)', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0005', 'account_name' => 'PENDAPATAN PENJUALAN MODUL PREBASIC', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0006', 'account_name' => 'PENDAPATAN PENJUALAN MODUL BASIC', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0007', 'account_name' => 'PENDAPATAN PENJUALAN MODUL INTERMEDIATE', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0008', 'account_name' => 'PENDAPATAN PENJUALAN MODUL ADVANCED', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0009', 'account_name' => 'PENDAPATAN PENJUALAN GELANG PREBASIC', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0010', 'account_name' => 'PENDAPATAN PENJUALAN GELANG BASIC', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0011', 'account_name' => 'PENDAPATAN PENJUALAN GELANG INTERMEDIATE', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0012', 'account_name' => 'PENDAPATAN PENJUALAN GELANG ADVANCED', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0013', 'account_name' => 'PENDAPATAN PENJUALAN TOTEBAG PREBASIC', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0014', 'account_name' => 'PENDAPATAN PENJUALAN TOTEBAG BASIC', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0015', 'account_name' => 'PENDAPATAN PENJUALAN TOTEBAG INTERMEDIATE', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0016', 'account_name' => 'PENDAPATAN PENJUALAN TOTEBAG ADVANCED', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0017', 'account_name' => 'PENDAPATAN PENJUALAN KAOS', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0018', 'account_name' => 'PENDAPATAN PENJUALAN GANTUNGAN KUNCI', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0019', 'account_name' => 'PENDAPATAN LAIN-LAIN', 'balance_type' => 'Debit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0020', 'account_name' => 'PENDAPATAN PENDAFTARAN SISWA', 'balance_type' => 'Debit', 'person_type' => 'Siswa'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0021', 'account_name' => 'SPP (KURSUS)', 'balance_type' => 'Debit', 'person_type' => 'Siswa'],
        ['account_type' => 'Pendapatan', 'account_code' => 'D 0022', 'account_name' => 'TRAINING INSTRUKTUR', 'balance_type' => 'Debit', 'person_type' => 'Karyawan'],

        // II - Pengeluaran / Beban
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0001', 'account_name' => 'BIAYA PEMBUKAAN LISENSI LC', 'balance_type' => 'Kredit', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0002', 'account_name' => 'BIAYA PEMBUKAAN LISENSI LO', 'balance_type' => 'Kredit', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0003', 'account_name' => 'BIAYA PERPANJANGAN LISENSI LC', 'balance_type' => 'Kredit', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0004', 'account_name' => 'BIAYA PERPANJANGAN LISENSI LO', 'balance_type' => 'Kredit', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0005', 'account_name' => 'BIAYA BELI MODUL PREBASIC', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0006', 'account_name' => 'BIAYA BELI MODUL BASIC', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0007', 'account_name' => 'BIAYA BELI MODUL INTERMEDIATE', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0008', 'account_name' => 'BIAYA BELI MODUL ADVANCED', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0009', 'account_name' => 'BIAYA CETAK MODUL PREBASIC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0010', 'account_name' => 'BIAYA CETAK MODUL BASIC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0011', 'account_name' => 'BIAYA CETAK MODUL INTERMEDIATE', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0012', 'account_name' => 'BIAYA CETAK MODUL ADVANCED', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0013', 'account_name' => 'BIAYA BELI GELANG PREBASIC', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0014', 'account_name' => 'BIAYA BELI GELANG BASIC', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0015', 'account_name' => 'BIAYA BELI GELANG INTERMEDIATE', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0016', 'account_name' => 'BIAYA BELI GELANG ADVANCED', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0017', 'account_name' => 'BIAYA CETAK GELANG PREBASIC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0018', 'account_name' => 'BIAYA CETAK GELANG BASIC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0019', 'account_name' => 'BIAYA CETAK GELANG INTERMEDIATE', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0020', 'account_name' => 'BIAYA CETAK GELANG ADVANCED', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0021', 'account_name' => 'BIAYA BELI TOTEBAG PREBASIC', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0022', 'account_name' => 'BIAYA BELI TOTEBAG BASIC', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0023', 'account_name' => 'BIAYA BELI TOTEBAG INTERMEDIATE', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0024', 'account_name' => 'BIAYA BELI TOTEBAG ADVANCED', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0025', 'account_name' => 'BIAYA CETAK TOTEBAG PREBASIC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0026', 'account_name' => 'BIAYA CETAK TOTEBAG BASIC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0027', 'account_name' => 'BIAYA CETAK TOTEBAG INTERMEDIATE', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0028', 'account_name' => 'BIAYA CETAK TOTEBAG ADVANCED', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0029', 'account_name' => 'BIAYA BELI KAOS', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0030', 'account_name' => 'BIAYA CETAK KAOS', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0031', 'account_name' => 'BIAYA BELI GANTUNGAN KUNCI', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0032', 'account_name' => 'BIAYA CETAK GANTUNGAN KUNCI', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0033', 'account_name' => 'BIAYA LAIN LAIN', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0034', 'account_name' => 'BIAYA TRAINING INSTRUKTUR', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0035', 'account_name' => 'BIAYA MARKETING', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0036', 'account_name' => 'BIAYA EVENT', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0037', 'account_name' => 'BIAYA TRANSPORTASI', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0038', 'account_name' => 'BIAYA DIGITAL', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0039', 'account_name' => 'BIAYA GAJI', 'balance_type' => 'Kredit', 'person_type' => 'Karyawan'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0040', 'account_name' => 'BIAYA FEE & BONUS', 'balance_type' => 'Kredit', 'person_type' => 'Karyawan'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0041', 'account_name' => 'BIAYA PACKING', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0042', 'account_name' => 'BIAYA KIRIM PAKET', 'balance_type' => 'Kredit', 'person_type' => 'Lisensi'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0043', 'account_name' => 'BIAYA KONSUMSI', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0044', 'account_name' => 'BIAYA ATK & FC', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0045', 'account_name' => 'BIAYA LISTRIK, AIR, PULSA, WIFI', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0046', 'account_name' => 'BIAYA PERALATAN KTR, PERLENGKAPAN KTR, PERLENGKAPAN RUMAH TANGGA KTR', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0047', 'account_name' => 'BIAYA FC, PRINT & BENDEL', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0048', 'account_name' => 'BIAYA ADMINISTRASI REKENING', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0049', 'account_name' => 'BIAYA SEWA RUKO', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0050', 'account_name' => 'BIAYA KEAMANAN', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0051', 'account_name' => 'BIAYA PARKIR', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0052', 'account_name' => 'BIAYA PAJAK', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0053', 'account_name' => 'BIAYA MEUBELER', 'balance_type' => 'Kredit'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0054', 'account_name' => 'BIAYA PENDAFTARAN SISWA', 'balance_type' => 'Kredit', 'person_type' => 'Siswa'],
        ['account_type' => 'Pengeluaran', 'account_code' => 'K 0055', 'account_name' => 'BIAYA SPP', 'balance_type' => 'Kredit', 'person_type' => 'Siswa'],

        // III - Cash
        ['account_type' => 'Cash', 'account_code' => 'C 0001', 'account_name' => 'PETTY CASH', 'balance_type' => 'Modal'],
        ['account_type' => 'Cash', 'account_code' => 'C 0003', 'account_name' => 'MODAL', 'balance_type' => 'Modal'],
    ],
];